import { Thought, User } from '@/types';

export const MOCK_ME: User = {
  id: 'user-001',
  username: 'JordanSays',
  displayName: 'Jordan',
  bio: 'I like questioning the obvious.',
  avatar: '',
  joinedDate: '2024-03-01',
  thoughtCount: 14,
  followerCount: 87,
  followingCount: 34,
  agreementCount: 312,
  disagreementCount: 58,
  discussionCount: 143,
};

export const MOCK_THOUGHTS: Thought[] = [
  {
    id: 'th-001',
    authorId: 'user-002',
    author: { username: 'MayaThinks', displayName: 'Maya', avatar: '' },
    title: 'Being busy has become a status symbol',
    preview: 'We treat exhaustion like a badge of honor. No one admits they have free time anymore.',
    body: "We treat exhaustion like a badge of honor. No one admits they have free time anymore. The first thing people say when you ask how they're doing is 'so busy'. It's become a way to signal importance. But I think we've lost something — the ability to just exist without performing productivity. Rest has been pathologized. Leisure feels guilty. And we've all quietly agreed to compete over who suffers more.",
    category: 'Work & Career',
    geo: { scope: 'Global', label: 'Global' },
    publishedAt: '2026-08-08T06:14:00Z',
    isRead: false,
    isSaved: false,
    isDraft: false,
    agreeCount: 214,
    disagreeCount: 31,
    discussionCount: 87,
    tags: ['work', 'culture', 'productivity'],
  },
  {
    id: 'th-002',
    authorId: 'user-003',
    author: { username: 'NixWrites', displayName: 'Nix', avatar: '' },
    title: 'Kampala traffic changed how I plan my day',
    preview: 'I stopped booking anything before 10am. The city forced me to restructure my whole life.',
    body: "I stopped booking anything before 10am. The city forced me to restructure my whole life. Three years ago I thought I was disciplined — 7am meetings, early starts. Then I moved to Kampala. Now I understand that discipline is relative to your environment. I work with the city, not against it. Late mornings, late nights. It's actually made me more productive, just on different terms.",
    category: 'Travel & Places',
    geo: { scope: 'City', label: 'Kampala', flag: '🇺🇬' },
    publishedAt: '2026-08-08T05:50:00Z',
    isRead: false,
    isSaved: true,
    isDraft: false,
    agreeCount: 98,
    disagreeCount: 12,
    discussionCount: 44,
    tags: ['city', 'travel', 'lifestyle'],
  },
  {
    id: 'th-003',
    authorId: 'user-004',
    author: { username: 'DavidK', displayName: 'David', avatar: '' },
    title: 'Most advice on social media is written for the advisor',
    preview: "It makes the writer feel wise. It rarely accounts for the reader's actual situation.",
    body: "It makes the writer feel wise. It rarely accounts for the reader's actual situation. 'Wake up at 5am.' 'Say no to everything.' 'Invest early.' All of it sounds like wisdom until you're a night-shift nurse, a caregiver, or in debt just to eat. Advice is autobiography. It tells you who the speaker is, not what you should do.",
    category: 'Society',
    geo: { scope: 'Global', label: 'Global' },
    publishedAt: '2026-08-07T22:31:00Z',
    isRead: true,
    isSaved: false,
    isDraft: false,
    agreeCount: 456,
    disagreeCount: 23,
    discussionCount: 201,
    tags: ['advice', 'social media', 'reality'],
  },
  {
    id: 'th-004',
    authorId: 'user-005',
    author: { username: 'SarahObserves', displayName: 'Sarah', avatar: '' },
    title: 'Therapy has a class problem no one talks about',
    preview: 'The people who need it most can rarely afford it. The people who can afford it use it as a lifestyle accessory.',
    body: "The people who need it most can rarely afford it. The people who can afford it use it as a lifestyle accessory. I'm not against therapy — I think it's genuinely valuable. But the way we've culturally positioned it as the universal solution ignores that $200/hour is not accessible to most people on earth. Meanwhile, community, religion, and other support systems that served the same function get dismissed as backward. We've privatized emotional health.",
    category: 'Health & Wellbeing',
    geo: { scope: 'Country', label: 'United States', flag: '🇺🇸' },
    publishedAt: '2026-08-07T18:12:00Z',
    isRead: true,
    isSaved: true,
    isDraft: false,
    agreeCount: 723,
    disagreeCount: 89,
    discussionCount: 334,
    tags: ['mental health', 'class', 'society'],
  },
  {
    id: 'th-005',
    authorId: 'user-006',
    author: { username: 'LeoBelieves', displayName: 'Leo', avatar: '' },
    title: 'We are raising children to fear failure instead of learn from it',
    preview: 'Every participation trophy, every protected grade — we are optimizing for confidence while removing resilience.',
    body: "Every participation trophy, every protected grade — we are optimizing for confidence while removing resilience. Real growth requires failure. It requires sitting with disappointment and finding a way through. When we sanitize childhood from all setbacks, we produce adults who collapse at the first real obstacle. Not because they are weak. Because no one let them practice being uncomfortable.",
    category: 'Education',
    geo: { scope: 'Global', label: 'Global' },
    publishedAt: '2026-08-07T14:45:00Z',
    isRead: false,
    isSaved: false,
    isDraft: false,
    agreeCount: 381,
    disagreeCount: 147,
    discussionCount: 289,
    tags: ['parenting', 'education', 'resilience'],
  },
  {
    id: 'th-006',
    authorId: 'user-007',
    author: { username: 'AminaReflects', displayName: 'Amina', avatar: '' },
    title: 'Lagos taught me that ambition without community is loneliness',
    preview: 'Everyone is grinding alone here. We chase individual success and wonder why we feel empty at the top.',
    body: "Everyone is grinding alone here. We chase individual success and wonder why we feel empty at the top. Lagos is a city of extraordinary ambition. People work incredibly hard. But somewhere in that hustle, the network became transactional. You call people when you need something. You show up when there is benefit. The deep, unconditional community I grew up watching is eroding. And we are calling it progress.",
    category: 'Life',
    geo: { scope: 'City', label: 'Lagos', flag: '🇳🇬' },
    publishedAt: '2026-08-07T10:02:00Z',
    isRead: true,
    isSaved: false,
    isDraft: false,
    agreeCount: 512,
    disagreeCount: 34,
    discussionCount: 178,
    tags: ['community', 'ambition', 'Africa'],
  },
  {
    id: 'th-007',
    authorId: 'user-008',
    author: { username: 'RafaelSpeaks', displayName: 'Rafael', avatar: '' },
    title: 'Democracy is becoming a performance we all agree to watch',
    preview: 'We vote, argue, debate — and then nothing fundamentally changes for most people.',
    body: "We vote, argue, debate — and then nothing fundamentally changes for most people. I am not cynical about democracy as an ideal. I think representation matters. But the version of democracy most countries are running has become more spectacle than substance. The real decisions happen elsewhere. Elections give people the feeling of agency without the substance of it. And we keep accepting the performance because the alternative terrifies us.",
    category: 'Politics',
    geo: { scope: 'Global', label: 'Global' },
    publishedAt: '2026-08-06T20:55:00Z',
    isRead: false,
    isSaved: false,
    isDraft: false,
    agreeCount: 644,
    disagreeCount: 312,
    discussionCount: 567,
    tags: ['politics', 'democracy', 'power'],
  },
  {
    id: 'th-008',
    authorId: 'user-009',
    author: { username: 'ZaraWonders', displayName: 'Zara', avatar: '' },
    title: 'AI is making us more confident and less competent',
    preview: 'We outsource thinking so gradually that we do not notice the skill disappearing.',
    body: "We outsource thinking so gradually that we do not notice the skill disappearing. I use AI tools. I find them genuinely helpful. But I have also noticed something in myself and in the people I work with: we reach for the tool before we attempt the thought. The friction that used to build capability — struggling through a problem, writing badly before writing well — is being removed. Efficiency and atrophy can look identical in the short run.",
    category: 'Technology',
    geo: { scope: 'Global', label: 'Global' },
    publishedAt: '2026-08-06T16:30:00Z',
    isRead: true,
    isSaved: true,
    isDraft: false,
    agreeCount: 892,
    disagreeCount: 441,
    discussionCount: 623,
    tags: ['AI', 'technology', 'cognition'],
  },
];

export const DRAFT_THOUGHTS: Thought[] = [
  {
    id: 'draft-001',
    authorId: 'user-001',
    author: { username: 'JordanSays', displayName: 'Jordan', avatar: '' },
    title: 'Friendship in your 30s is scheduled kindness',
    preview: 'We still care. We just stopped showing up without a calendar invite.',
    body: 'We still care. We just stopped showing up without a calendar invite. I think about this a lot. In your 20s, friendship was ambient — you just existed near each other. Now it requires activation energy. You have to decide to prioritize it...',
    category: 'Friendship',
    geo: { scope: 'Global', label: 'Global' },
    publishedAt: '2026-08-08T04:00:00Z',
    isRead: true,
    isSaved: false,
    isDraft: true,
    agreeCount: 0,
    disagreeCount: 0,
    discussionCount: 0,
    tags: [],
  },
];

export const MY_THOUGHTS: Thought[] = [
  {
    id: 'my-001',
    authorId: 'user-001',
    author: { username: 'JordanSays', displayName: 'Jordan', avatar: '' },
    title: 'Silence in an argument is not losing',
    preview: 'Sometimes walking away is the most articulate thing you can say.',
    body: 'Sometimes walking away is the most articulate thing you can say. I used to think that not responding meant I had no answer. Now I understand that not every provocation deserves a reply. Some arguments are not conversations — they are performances. Refusing to perform is its own kind of clarity.',
    category: 'Relationships',
    geo: { scope: 'Global', label: 'Global' },
    publishedAt: '2026-08-05T11:22:00Z',
    isRead: true,
    isSaved: false,
    isDraft: false,
    agreeCount: 187,
    disagreeCount: 23,
    discussionCount: 64,
    tags: ['communication', 'relationships'],
  },
];
